Repository ICOS-Carbon-Portal/pylib, pull requests merged in 2022-09, with the labels that each got.

#95 update cpb module docs for 0.1.15
  docs/examples.md
  docs/faq.md
  docs/img/dobj_minimal.png
  docs/img/dobj_title.png
  docs/index.md
  docs/install.md
  docs/modules.md
Labels: documentation, enhancement

#99 ad station.getList('AS')
  icoscp/sparql/sparqls.py
  icoscp/station/station.py
Labels: fix

#104 Fix query and remove some sparql runs.
  icoscp/sparql/sparqls.py
  icoscp/station/station.py
Labels: enhancement, fix, deprecation

#105 103 regenerate json file in stilt module
  icoscp/stilt/stations.json
Labels: enhancement

#106 zz patch release 0.1.16
  dist/icoscp-0.1.16-py3-none-any.whl
  dist/icoscp-0.1.16.tar.gz
  docs/changelog.md
  icoscp.egg-info/PKG-INFO
  icoscp/__init__.py
  setup.py
Labels: release, [patch]
