Repository ICOS-Carbon-Portal/pylib, pull requests merged in 2022-11, with the labels that each got.

#112 101 problems when building the library
  setup.py
Labels: fix

#114 113 patch release 0.1.17
  dist/icoscp-0.1.17-py3-none-any.whl
  dist/icoscp-0.1.17.tar.gz
  docs/changelog.md
  icoscp.egg-info/PKG-INFO
  icoscp.egg-info/SOURCES.txt
  icoscp/__init__.py
  setup.py
Labels: release, [patch]

#115 update readme.md
  README.md
Labels: documentation, enhancement

#116 release 0.1.18a
  setup.py
Labels: enhancement
